#!/bin/bash
logger -i "Backup started"

DATE=`date +%d-%m-%Y`
FILENAME=backup-$DATE.tar.gz
FILENAMEFULL=FULL-backup-$DATE.tar.gz
SRCDIR=/
SRCDIRS="/home/pi/ /etc/" 
DESDIR=/media/USBHDD/backups            # Destination of backup file.

# remove backups older than 14 days
sudo find /media/USBHDD/backups -mtime +13 -printf "%f\n" -exec rm {} \;

#If sunday do FULL backup
if [[ $(date '+%a') == "Sun" || "$1" == "full" ]]; then
   sudo tar -cpzf $DESDIR/$FILENAMEFULL --exclude=/media --exclude=/dev --exclude=/mnt --exclude=/proc --exclude=/tmp --exclude=/sys --exclude=/run $SRCDIR
else
   # do the backup
   sudo tar -cpzf $DESDIR/$FILENAME $SRCDIRS
fi

logger -i "Backup completed"
